import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          background: 'linear-gradient(to bottom, #ADD8E6 90%, #90EE90 10%)',
          backgroundAttachment: 'fixed', // 背景を固定
          backgroundSize: '100% 100vh', // 背景サイズを調整
          minHeight: '100vh',
        }}
      >
        {children}
      </body>
    </html>
  );
}
